### ISSUE TITLE
Panic with simple http request

### ISSUE THREAD

**Issue by l1x** [jayjamesjay/http_req#17]
Hi,

I am not sure what is happening:

Cargo.toml:

`http_req  = {version="0.4.9", default-features = false, features = ["rust-tls"]}
`

```rust
fn fetch_adlist() {
    let adlist_url = "https://gist.githubusercontent.com/l1x/51e7ec94526dc7d0aba77b31378df48b/raw/a4515ac76d41a29df971e4ceab9e9916b71eea1b/tmux.conf";
    let mut writer = Vec::new();
    let res = request::get(adlist_url, &mut writer);
    match res {
        Ok(res) => info!("Status: {} {}", res.status_code(), res.reason()),
        Err(err) => debug!("{:?}", err),
    }
}
```

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
```

**Comment by jayjamesjay** [comment]
The error occurs during parsing headers. I made a wrong assumption that every header contains both double colon and space. It turned out that some headers might contain double colon without the following space / have no value.

I've already prepared the update and I'll release it soon.
