### ISSUE TITLE
Uri::from_str(<ipv6>) fails

### ISSUE THREAD

**Issue by valeriansaliou** [jayjamesjay/http_req#21]
Hello!

First of all, thanks for the lightweight library.

I've noticed that raw IPv6 addresses in HTTP URLs cannot be parsed as an internal Uri, and thus cannot be connected to.

**Here's an example of a valid URL w/ an IPv6 address:**

`https://[2a03:b0c0:3:d0::ba8:8001]:443/`

**And the error that's generated when attempting to `.parse()` the URL string:**

`Err(Parse(UriErr))`

**Comment by valeriansaliou** [comment]
URL generator code from: https://github.com/valeriansaliou/constellation/blob/master/src/dns/health.rs#L449

**Comment by jayjamesjay** [comment]
Thank you for reporting the issue. I think I've resolved it. Please let me know if everything works as expected.

**Comment by valeriansaliou** [comment]
Thanks. The Uri parser now works. Perfect!
