### ISSUE TITLE
Relative paths aren't parsed

### ISSUE THREAD

**Issue by isavegas** [jayjamesjay/http_req#22]
Relative URis such as `/path` aren't handled correctly. Rather than `.path()` and `.resource()` returning `/path`, they simply return `None`.

```rust
use http_req::uri::Uri;
fn main() {
	// I am expecting `Some("/path")` but receive `None`
	println!("{:?}", "/path".parse::<Uri>().path());
}
```

**Comment by jayjamesjay** [comment]
I'm sorry to say it, but `Uri` does currently not support relative URIs.
It supports URIs following the general syntax from [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3)

**Comment by isavegas** [comment]
Dang, alrighty. Would you like to add support? I thought about submitting a pull request, but I wasn't up to messing with it at the time.

**Comment by jayjamesjay** [comment]
I wasn't going to add support for it soon. You can freely make a pull request, if you want to.
