### ISSUE TITLE
Documentation on connection timeout is misleading

### ISSUE THREAD

**Issue by Shnatsel** [jayjamesjay/http_req#27]
[Documentation for `connect_timeout()`](https://docs.rs/http_req/0.5.4/http_req/request/struct.Request.html#method.connect_timeout) states:

> If None is provided, TcpStream::connect will be used, and it will not time out.

This is not actually true: TCP connection attempts will time out, and this is enforced by the operating system.

Here's how it works on Linux and Mac OS: http://willbryant.net/overriding_the_default_linux_kernel_20_second_tcp_socket_connect_timeout

Windows also enforces a timeout: https://serverfault.com/questions/193160/which-is-the-default-tcp-connect-timeout-in-windows

For reference, all other Rust HTTP client libraries do not set a default connection timeout, while libcurl sets it to 300 seconds by default.

**Comment by jayjamesjay** [comment]
Thank you for pointing this out. I will correct the documentation.

**Comment by jayjamesjay** [comment]
I've updated the docs for [`connect_timeout`](https://docs.rs/http_req/0.5.5/http_req/request/struct.Request.html#method.connect_timeout)

> If `None` is provided, `TcpStream::connect` will be used. Timeot **will depend on the platform.**

**Comment by Shnatsel** [comment]
I'd go with something like

> If `None` is provided, `TcpStream::connect` will be used. **A timeout will still be enforced** by the operating system, but the exact value depends on the platform.
