### ISSUE TITLE
No way to set timeout for the entire request, which allows DoS attacks

### ISSUE THREAD

**Issue by Shnatsel** [jayjamesjay/http_req#28]
http_req currently does not allow specifying a timeout for the entire request (i.e. until the request body is finished transferring), which means an established connection will keep going indefinitely if the remote host keeps replying.

This is fine for the simple use cases, like a user downloading something interactively, but enables denial-of-service attacks in automated scenarios: if the remote host keeps transferring data at a really low speed, e.g. several bytes per second, the connection will be open indefinitely. This makes it easy for an attacker who can submit URLs to the server to cause denial of service through some kind of resource exhaustion - running out of RAM, networking ports, etc.

**Comment by jayjamesjay** [comment]
Thank you for informing about this issue. It seems to be pretty serious but I'm not sure how exactly I'm supposed to fix it. Would you give me some advice about possible implementation of a fix?

**Comment by Shnatsel** [comment]
Yes, I have an idea how this could be implemented. See https://github.com/algesten/ureq/issues/28 and https://github.com/sbstp/attohttpc/issues/35

**Comment by Shnatsel** [comment]
A simple implementation of a timeout for the entire request can be viewed here: https://github.com/neonmoe/minreq/commit/41ef16e33501712e64a5711a7f4bc132d9bfbe40
However, if used as-is it may have a significant performance penalty.

**Comment by jayjamesjay** [comment]
Thanks, I'll take a look at them.

**Comment by Shnatsel** [comment]
An alternative approach to the implementation can be found here: https://github.com/sbstp/attohttpc/pull/47

**Comment by jayjamesjay** [comment]
@Shnatsel what do you think about this (branch `timeout`) implementation? Does it solves the problem? Do you think timeout of 3 hours is good enough?

**Comment by Shnatsel** [comment]
Thanks for tackling this! I've commented on the PR: https://github.com/jayjamesjay/http_req/pull/33
