### ISSUE TITLE
Cannot send http post request with body

### ISSUE THREAD

**Issue by m3ngzhang** [jayjamesjay/http_req#39]
Hi, I am working with this repo to send a post request to my server. But I always get a error, which is "status":400,"error":"Bad Request","message":"Required request body is missing:...". It seams that the server cannot get the body. Please help me out.

**Comment by jayjamesjay** [comment]
There's a little misleading in [docs](https://docs.rs/http_req/0.6.1/http_req/request/struct.Request.html#method.body). In order to make a `POST` request, you need to set request method to `POST`, set request's `body` and add header `Content-Length` with value of body length. Here's a simple example.
```rust
use http_req::{
    request::{Method, Request},
    uri::Uri,
};

fn main() {
    let mut writer = Vec::new();
    let uri: Uri = "https://http.requestcatcher.com/test ".parse().unwrap();
    const body: &[u8; 27] = b"field1=value1&field2=value2";

    let response = Request::new(&uri)
        .method(Method::POST)
        .body(body)
        .header("Content-Length", &body.len()) //This is important
        .send(&mut writer)
        .unwrap();

    println!("{}", response.status_code());
}
```

**Comment by m3ngzhang** [comment]
Finally, it works, bro!

**Comment by cjqpker** [comment]
> There's a little misleading in [docs](https://docs.rs/http_req/0.6.1/http_req/request/struct.Request.html#method.body). In order to make a `POST` request, you need to set request method to `POST`, set request's `body` and add header `Content-Length` with value of body length. Here's a simple example.
> 
> ```rust
> use http_req::{
>     request::{Method, Request},
>     uri::Uri,
> };
> 
> fn main() {
>     let mut writer = Vec::new();
>     let uri: Uri = "https://http.requestcatcher.com/test ".parse().unwrap();
>     const body: &[u8; 27] = b"field1=value1&field2=value2";
> 
>     let response = Request::new(&uri)
>         .method(Method::POST)
>         .body(body)
>         .header("Content-Length", &body.len()) //This is important
>         .send(&mut writer)
>         .unwrap();
> 
>     println!("{}", response.status_code());
> }
> ```

I'm here with the same problem, but I got no error and the server received a body with zero length.

Maybe ”Content-Length“ should be added automaticly when method is "POST", or it's so hard to debug this unexpected behavior
