### ISSUE TITLE
Uri::from_str("https://bing.com") fails

### ISSUE THREAD

**Issue by ghost** [jayjamesjay/http_req#4]
Hello,

In version `0.4.4` this call fails: `Uri::from_str("https://bing.com")`.

May I ask if you could fix?

Thank you,

**Comment by jayjamesjay** [comment]
Could describe this issue in more detail?
What is the compiler error?
Does it only occur with this specific url?

**Comment by ghost** [comment]
Thank you for your reply.

I apologize, I must have made up something in my head. Now testing it again, it produces perfect result.

Thank you again. I really admire your hard work, that you've been able to keep dependencies at minimum.
