### ISSUE TITLE
cant add headers to existing request

### ISSUE THREAD

**Issue by 89z** [jayjamesjay/http_req#52]
Using this code:

~~~rust
use http_req::{request::Request, uri::Uri, response::Headers};
use std::convert::TryFrom;

fn main() {
   let uri: Uri = Uri::try_from("https://www.rust-lang.org/learn").unwrap();
   let mut headers = Headers::new();
   headers.insert("Connection", "Close");
   let req = Request::new(&uri).headers(headers);
   println!("{:?}", req);
}
~~~

I get this result:

~~~
creates a temporary which is freed while still in use
~~~

if I change to this:

~~~rust
let req = Request::new(&uri);
req = req.headers(headers);
~~~

I get a different error:

~~~
expected struct `Request`, found `&mut Request<'_>`
~~~

**Comment by jayjamesjay** [comment]
`Request` has been created with the builder pattern in mind. Many methods like `headers` are used to set different properties of the request. While the `send` method is used to execute the request. 

A cause of the second error is the fact that `new` method returs a mutable reference to the request.

More information alongside with some examples can be found in the [docs](https://docs.rs/http_req/latest/http_req/request/struct.Request.html#method.headers).

**Comment by 89z** [comment]
thank you - I reviews those docs previously - but it doesn't seem possible to actually print a Request object

**Comment by 89z** [comment]
OK this seems to work:

~~~rust
let mut req = Request::new(&uri);
let req = req.header("Connection", "Close");
~~~

its just awkward needing to use `let` twice. I suspect this is due to design decision of the `http_req` package.
