### ISSUE TITLE
Update rustls to 0.21.7

### ISSUE THREAD

**Issue by DamienVoreiter** [jayjamesjay/http_req#59]
Hi,
I want to get my dependencies up to date but I'm blocked with rustls as you use version 0.17.

Is it possible to update rustls to 0.21.7 ?
Thanks !

**Comment by DamienVoreiter** [comment]
Hello @jayjamesjay,
I tried to create a PR which update rustls from 0.19 to 0.21. https://github.com/jayjamesjay/http_req/pull/60
Can you take a look and tell me if it's ok for you or if you want me to do some changes ? 

Thanks ! 🙏

**Comment by jayjamesjay** [comment]
Thank you. I'll check it out and get back to you.

**Comment by jayjamesjay** [comment]
Changes has been added to the branch [v0.10](https://github.com/jayjamesjay/http_req/tree/v0.10). They will become a part of next release.

**Comment by DamienVoreiter** [comment]
nice thank you !
