### ISSUE TITLE
Feature request: read timeout

### ISSUE THREAD

**Issue by ghost** [jayjamesjay/http_req#6]
Hi,

Currently there is no option for read timeout on internal `TcpStream` instances. May I ask if you could add new option(s) for that?

I would like to code and send you a pull request for your review. If you agree, please let me know so I can start. Please give me some directions, such as:

- Name of new function(s).
- Place(s) where to put them.
- Should those functions take a `Duration`, or `Option<Duration>`? If it's an `Option`, which default value should be?
- ...

Thank you,

**Comment by jayjamesjay** [comment]
Feel free to send pull requests. I don't have any requirements about naming functions, places where to them, etc.. Just stick to the rules of idiomatic Rust.
