### ISSUE TITLE
Make stream public in Conn struct

### ISSUE THREAD

**Issue by DamienVoreiter** [jayjamesjay/http_req#61]
Hello @jayjamesjay,
Is it possible for you to make `stream` public in `Conn` structure to be able to create a `Conn` ?

I need to be able to do things like
```
...
let stream = StreamOwned::new(session, stream);
Ok(Conn { stream })
```

I make a PR if it's ok for you https://github.com/jayjamesjay/http_req/pull/62 😃

**Comment by jayjamesjay** [comment]
Thanks for the comment. Honestly speaking I would be prefer to avoid it. Would you be able to achieve the desired outcome with something like getter / setter method?

**Comment by DamienVoreiter** [comment]
Me neither, I try again to do this with getter/setter but I think I missing something. I'll keep you informed

**Comment by DamienVoreiter** [comment]
@jayjamesjay I check quickly and it seams it missing some setter for my usage. I need to change (or have a default value) for key_log, ct_logs, certificate_verifier, client_auth_cert_resolver
Do you want me to implement default values in Config ? Or some setter ?

**Comment by jayjamesjay** [comment]
If that's possible please start with some setter. I think that should be more robust solution.

**Comment by DamienVoreiter** [comment]
yes totally agree, I try to create an other PR with setter and ping you want it's ok on my side

**Comment by DamienVoreiter** [comment]
re @jayjamesjay, 
I try to add some setter and stuff to personalize ClientConfig (not sure of what I did 🤔)
https://github.com/jayjamesjay/http_req/pull/64 if you want to take a look

**Comment by jayjamesjay** [comment]
Thanks for the contribution. Honestly speaking, it's hard for me to analyze and / or improve it, because I don't `rustls` that well. For now I will not add this changes. I may come back to it in future.

**Comment by DamienVoreiter** [comment]
ok no problem I understand. I'll try to do this on an other way, thanks for your answer
